# Generated by Django 5.0.3 on 2024-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("tid", models.AutoField(primary_key=True, serialize=False)),
                ("task", models.CharField(max_length=20)),
                ("time", models.DateTimeField()),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Task",
            },
        ),
    ]
