# Generated by Django 5.0.3 on 2024-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Done"),
        ),
    ]
