# Generated by Django 5.0.3 on 2024-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="time",
            field=models.TimeField(),
        ),
    ]
