# Generated by Django 5.0.3 on 2024-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("sid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "Store",
            },
        ),
    ]
