# Generated by Django 5.0.3 on 2024-03-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address",
            new_name="details",
        ),
    ]
