# Generated by Django 5.0.3 on 2024-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("mid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=50)),
                ("date_released", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "Movie",
            },
        ),
    ]
