# Generated by Django 5.0.3 on 2024-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("bid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=80)),
                ("content", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=60)),
                ("date_published", models.DateField()),
            ],
            options={
                "db_table": "Blog",
            },
        ),
    ]
