# Generated by Django 5.0.3 on 2024-03-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("rollno", models.PositiveSmallIntegerField()),
                ("subject", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
