# Generated by Django 5.0.3 on 2024-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
