# Generated by Django 5.0.3 on 2024-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("Eid", models.AutoField(primary_key=True, serialize=False)),
                ("Ename", models.CharField(max_length=200)),
                ("Eemail", models.EmailField(max_length=254)),
                ("Econtact", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
