# Generated by Django 5.0.3 on 2024-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "rollno",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("subject", models.CharField(max_length=50)),
            ],
        ),
    ]
