# Generated by Django 5.0.3 on 2024-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("date_published", models.DateField()),
                ("no_of_pages", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
