# Generated by Django 5.0.3 on 2024-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="date_published",
            field=models.DateField(auto_now_add=True),
        ),
    ]
